# Generated by Django 5.0.3 on 2024-03-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='proximafecha',
            name='descripcion',
            field=models.CharField(default='La música existe para cuando nos fallan las palabras.', max_length=100),
        ),
        migrations.AddField(
            model_name='proximafecha',
            name='img',
            field=models.ImageField(default='../media/imagenes/concierto.jpg', upload_to='avatares'),
        ),
    ]
